apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: mobile-gateway
  description: API Gateway for mobile requests
spec:
  type: openapi
  lifecycle: production
  owner: group:default/integration-team
  providesApis:
    - api:default/mobile-app
  consumesApis:
    - api:default/transfer-engine  # Calls Transfer Engine API
  definition: |
    openapi: 3.0.0
    info:
      title: Mobile Gateway API
      version: 1.0.0
    paths: {}

